# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salesperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
